### ISSUE TITLE
Old convention for versions is listed ahead of new convention

### ISSUE THREAD

**Issue by cvirtucio** [nklmilojevic/asdf-helix#2]
**Describe the bug**

This plugin lists the old convention (`v$semver`) ahead of the new convention (`$major.minor`), resulting in 404s when trying to install the "latest" version of `helix`.

**Steps to reproduce**

1. Add this plugin with either `asdf` or `mise`.
2. Configure your tool of choice to pull the latest version of this plugin.
3. Run the install command for your tool.

**Expected behavior**

Latest version (`24.07` as of time of writing) is installed.

**Screenshots**

**Additional context**

[PR with suggested changes](https://github.com/nklmilojevic/asdf-helix/pull/1).

**Comment by nklmilojevic** [comment]
Thanks!
